### ISSUE TITLE
Persistence queue does not seem to persist between sessions

### ISSUE THREAD

**Issue by rafaellehmkuhl** [PostHog/posthog-js-lite#324] opened 2024-12-06 14:21 UTC
## Bug description

I have an application where [I'm implementing event-tracking with PostHog](https://github.com/bluerobotics/cockpit/pull/1482). This application is mainly used offline, as it's a mission app. Users usually go to the field, use it several times while offline, and eventually go back home and open it again, now online.

I use Sentry for error-tracking, and it stores the events in the IndexedDB. I'm trying PostHog for event-tracking, and initially it seemed to have persistence options in the library, but after testing a little bit and reading the docs, it seems like its only persisting configuration and user-data, but not the events queue.

In #176 it is mentioned the existence of an offline queue, but it seems to be working only during the session, this is, if the user comes back online without closing the application, the events in the queue will be sent, but if not, they will be lost when the user closes the application.

I'm opening as a bug report because it seems like an undesired behavior, since for offline-first apps this means losing most of the events, but I understand it can be considered a feature request. No problem if the maintainers see it in that way and change the tags.

As a workaround I'm going to implement the persistence on my side, as I liked PostHog a lot. If you see an opening for merging the feature in this library, let me know.

## How to reproduce

1. Open you application while online
2. Capture an event
3. Go offline
4. Capture a new event
5. Close you application
6. Go online
7. Open your application again
8. The event that was captured while offline will never appear in the PostHog servers

**Comment by rafaellehmkuhl** [comment] 2024-12-06 14:31
I just realized this repository is not for the currently used JS library, so [I've reopened the issue there](https://github.com/PostHog/posthog-js/issues/1583). Feel free to close it if needed.

**Comment by daibhin** [comment] 2024-12-06 15:01
Hi @rafaellehmkuhl - can I confirm what platform / framework you're trying to include PostHog in?

**Comment by mhyassin** [comment] 2024-12-06 15:25
@daibhin Not the author, but we've posthog in react native & it seems like that we're suffering from the same issue, I can't really reproduce it but on our dashboards not all users get merged to their respective anonymous users after being identified

**Comment by marandaneto** [comment] 2024-12-09 10:46
> @daibhin Not the author, but we've posthog in react native & it seems like that we're suffering from the same issue, I can't really reproduce it but on our dashboards not all users get merged to their respective anonymous users after being identified

this seems to be a different issue, please raise a new issue with more context, thanks.

**Comment by marandaneto** [comment] 2024-12-09 10:47
Since this is not RN, closing in favor of https://github.com/PostHog/posthog-js/issues/1583

**Closed by marandaneto** 2024-12-09 10:47 UTC
Labels: bug
